[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plt-rs = { path = "../../.." }
libc = "0.2.137"

# utilities
libloading = "0.7"
proc-maps = "0.3.0"
